spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${application.spring.datasource.url}
    username: ${application.spring.datasource.username}
    password: ${application.spring.datasource.password}

  jpa:
    database: mysql
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

      ddl-auto: update # (1) 스키마 자동 생성
    show-sql: true # (2) SQL 쿼리 출력
    generate-ddl: true
    properties:
      hibernate:
        format_sql: true # (3) SQL pretty print

    defer-datasource-initialization: true

logging:
  level:
    root: info
    org:
      hibernate: info
      web: info